In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("./chartmode_data.csv")
data.head()

,Unnamed: 0,Unnamed: 0.1,株式コード,資本金,提出者名,業種,提出者業種,残業時間,有休消化率,待遇面の満足度,...,人材の長期育成,法令遵守意識,人事評価の適正感,時価総額,従業員数(単独),従業員数,平均年齢,平均年収,設立年,上場年
0,0,0,7203.T,635401.0,トヨタ自動車株式会社,機械系,輸送用機器,27.0,87.8,4.2,...,4.0,4.9,3.2,251.66,None,372434,40.0,8580,1937,1949
1,1,1,6861.T,30637.0,株式会社キーエンス,機械系,電気機器,59.6,29.2,4.8,...,2.6,3.9,4.3,154.37,"2,607人",8380,35.8,17510,1974,1987
2,2,2,6758.T,880214.0,ソニーグループ株式会社,機械系,電気機器,34.9,61.0,4.1,...,3.0,4.6,3.8,154.06,"2,973人",109700,42.2,10440,1946,1958
3,3,3,6098.T,40000.0,株式会社リクルートホールディングス,サービス業,サービス業,36.8,57.3,4.1,...,3.1,4.0,4.1,105.30,138人,47786,38.7,9500,1963,2014
4,4,4,9432.T,937950.0,日本電信電話株式会社,IT,IT,20.8,92.3,3.3,...,3.2,4.9,3.0,97.00,None,332950,41.8,9300,1985,1987

In [6]:
category_count = {}
for i in range(len(data)):
    if(data["業種"][i] in category_count):
        category_count[data["業種"][i]] += 1
    else:
        category_count[data["業種"][i]] = 1

In [7]:
print(category_count)

{'機械系': 54, 'サービス業': 8, 'IT': 21, '金融・保険': 24, '化学・石油・石炭': 18, '卸売・小売・食料': 29, 'その他': 24, '医薬品': 14, '運輸': 16, '建設・不動産': 11}